load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "ineffassign",
    srcs = ["analyzer.go"],
    importpath = "github.com/sluongng/nogo-analyzer/goci-lint/ineffassign",
    visibility = ["//visibility:public"],
    deps = ["@com_github_gordonklaus_ineffassign//pkg/ineffassign"],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "analyzer.go",
        "go.mod",
        "go.sum",
    ],
    visibility = ["//visibility:public"],
)
