load("@nogo-analyzer//private:go_bazel_test.bzl", "go_bazel_test")

go_bazel_test(
    name = "tests",
    size = "medium",
    srcs = ["staticcheck_test.go"],
    rule_files = [
        "@nogo-analyzer//:all_files",
        "@rules_go//:all_files",
        "@gazelle//:all_files",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "staticcheck_test.go",
    ],
    visibility = ["//visibility:public"],
)
