load("@rules_go//go:def.bzl", "go_test")
load("@rules_go//go/tools/bazel_testing:def.bzl", "go_bazel_test")

go_bazel_test(
    name = "tests",
    size = "medium",
    srcs = ["golangci_lint_test.go"],
    rule_files = [
        "@com_github_sluongng_nogo_analyzer//:all_files",
        "@rules_go//:all_files",
        "@gazelle//:all_files",
    ],
    tags = ["manual"],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "golangci_lint_test.go",
    ],
    visibility = ["//visibility:public"],
)

go_test(
    name = "tests_test",
    srcs = ["golangci_lint_test.go"],
    deps = ["@rules_go//go/tools/bazel_testing"],
)
