load("@gazelle//:def.bzl", "DEFAULT_LANGUAGES", "gazelle", "gazelle_binary")

# gazelle:exclude .user.bazelrc
# gazelle:exclude go.work.sum
# gazelle:exclude bazel-*
# gazelle:exclude examples/**

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        ".bazelrc",
        ".bazelversion",
        ".gitignore",
        "BUILD.bazel",
        "LICENSE",
        "MODULE.bazel",
        "MODULE.bazel.lock",
        "README.md",
        "WORKSPACE",
        "buildbuddy.yaml",
        "def.bzl",
        "go.work",
        "//.github:all_files",
        "//goci-lint:all_files",
        "//golangci-lint:all_files",
        "//private:all_files",
        "//staticcheck:all_files",
        "//tools:all_files",
    ],
    visibility = ["//visibility:public"],
)

gazelle_binary(
    name = "gazelle_binary",
    languages = DEFAULT_LANGUAGES + ["@gazelle//internal/language/test_filegroup"],
)

# gazelle:prefix github.com/sluongng/nogo-analyzer
gazelle(
    name = "gazelle",
    gazelle = "gazelle_binary",
)

alias(
    name = "goworksync",
    actual = "@nogo-analyzer//tools:goworksync",
)
