load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "prealloc",
    srcs = ["analyzer.go"],
    importpath = "github.com/sluongng/nogo-analyzer/goci-lint/prealloc",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golangci_prealloc//:prealloc",
        "@org_golang_x_tools//go/analysis",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "analyzer.go",
        "go.mod",
        "go.sum",
    ],
    visibility = ["//visibility:public"],
)
