sh_binary(
    name = "goworksync",
    srcs = ["goworksync.sh"],
    data = [
        "@rules_go//go",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_tools//tools/bash/runfiles",
    ],
)

filegroup(
    name = "all_files",
    testonly = True,
    srcs = [
        "BUILD.bazel",
        "goworksync.sh",
    ],
    visibility = ["//visibility:public"],
)
